POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/025a6c49-e137-416c-b9df-7e3a29a1a7db/attendees
Content-Type: application/json

{
    "name": "Clelton José Mielke",
    "email": "cleltonjm_95@otmail.com"
}

###

GET http://localhost:3333/events/025a6c49-e137-416c-b9df-7e3a29a1a7db

###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/3/check-in

###

GET http://localhost:3333/events/025a6c49-e137-416c-b9df-7e3a29a1a7db/attendees?query=clelton